"""Tiny, dependency-free PDF writer.

Real boleto PDFs are generated by a barcode/boleto-layout library (e.g. a
FEBRABAN-compliant renderer). Pulling one of those into a demo Lambda would
mean vendoring a heavy dependency just to prove the pipeline works, so this
module hand-writes a minimal, spec-valid single-page PDF with the boleto's
key fields as plain text. It's enough to prove "PDF generated -> stored in
S3 -> downloadable", which is the part the architecture actually cares about.
"""
from __future__ import annotations


def _escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def build_boleto_pdf(
    *, boleto_id: str, amount_cents: int, due_date: str, payer_name: str, payer_document_masked: str
) -> bytes:
    lines = [
        "BOLETO DE PAGAMENTO (DEMO)",
        f"Boleto ID: {boleto_id}",
        f"Valor: R$ {amount_cents / 100:.2f}",
        f"Vencimento: {due_date}",
        f"Pagador: {payer_name}",
        f"CPF/CNPJ: {payer_document_masked}",
        "Este e um documento de demonstracao gerado localmente.",
    ]

    content_stream = "BT /F1 16 Tf 50 740 Td 20 TL\n"
    for line in lines:
        content_stream += f"({_escape(line)}) Tj T*\n"
    content_stream += "ET"

    objects: list[str] = []
    objects.append("<< /Type /Catalog /Pages 2 0 R >>")
    objects.append("<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    objects.append(
        "<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> "
        "/MediaBox [0 0 612 792] /Contents 5 0 R >>"
    )
    objects.append("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    stream_bytes = content_stream.encode("latin-1")
    objects.append(f"<< /Length {len(stream_bytes)} >>\nstream\n{content_stream}\nendstream")

    header = b"%PDF-1.4\n"
    body_parts: list[bytes] = []
    offsets = [0]  # object 0 is free, placeholder
    cursor = len(header)
    for i, obj in enumerate(objects, start=1):
        obj_bytes = f"{i} 0 obj\n{obj}\nendobj\n".encode("latin-1")
        offsets.append(cursor)
        body_parts.append(obj_bytes)
        cursor += len(obj_bytes)

    xref_offset = cursor
    n = len(objects) + 1
    xref = f"xref\n0 {n}\n0000000000 65535 f \n"
    for off in offsets[1:]:
        xref += f"{off:010d} 00000 n \n"

    trailer = f"trailer\n<< /Size {n} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF"

    pdf = header + b"".join(body_parts) + xref.encode("latin-1") + trailer.encode("latin-1")
    return pdf
